---
# tasks file for ceph_log_parser
- set_fact:
    log_file: "{{ item.log_file }}"
    level: "{{ item.level }}"
    timeinterval: "{{ item.timeinterval }}"
    pg_line: "{{ item.pg_line }}"

- name: ceph_log_parser
  ceph_log_parser:
    log_file: "{{ log_file }}"
    level: "{{ level }}"
    timeinterval: "{{ timeinterval }}"
    pg_line: "{{ pg_line }}"
  register: datetime

- name: write csv findings
  local_action: 
    module: lineinfile 
    line: "{{ level }},{{ pg_line }},{{ inner_item.key }},{{ inner_item.value }}" 
    dest: "{{ logfile_dest }}"
  loop: "{{ datetime.msg | dict2items }}"
  loop_control:
    loop_var: inner_item
